version: '3.5'

services:
  app:
    container_name: app_container
    image: eui/api:8
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: db
      DB_PORT: 5432
      DB_SYNC: "true"
      PORT: 8080
    ports:
      - "3001:8080"
    networks:
      - postgres
    restart: unless-stopped
  